#!/usr/bin/env python
# -*- coding: utf-8 -*-

# core library
import sys

# addon libraries
from PyQt4.QtCore import *
from PyQt4.QtGui import *

# local imports
import controller

__version__ = "0.1"

app = QApplication(sys.argv)

control = controller.Controller()
control.start()

sys.exit(app.exec_())
# if it segfaults, blame the bindings, fixed in 4.7.4 i hope
